source: /home/andrea/Archivio_test/PHOTO_source
destination: /home/andrea/Archivio_test/OUT
database: /home/andrea/Archivio_test/archivio_migrazione.db
log: /home/andrea/Archivio_test/log_migrazione.txt

# Opzioni di esclusione
exclude_hidden_dirs: true  # Esclude directory che iniziano con '.'
exclude_patterns:          # Ulteriori pattern da escludere (opzionale)
  - .DS_Store
  - Thumbs.db
  - desktop.ini
  - .git
  - .svn
  - __pycache__
  - node_modules

supported_extensions:
  - .jpg
  - .jpeg
  - .png
  - .heic
  - .mp4
  - .mov
  - .avi
  - .mkv
  - .m2t
  - .3gp

image_extensions:
  - .jpg
  - .jpeg
  - .png
  - .heic

video_extensions:
  - .mp4
  - .mov
  - .avi
  - .mkv
  - .m2t
  - .3gp

photographic_prefixes:
  - JPG
  - IMG_
  - MVI_
  - MVC
  - CAN_
  - MG
  - DSC_
  - NDC_
  - _DSC
  - DSC
  - ILCE-
  - HDR
  - MOV
  - DSCF
  - FUJI
  - _DSF
  - LUMIX_
  - OMD_
  - PENTX
  - LEICA_
  - GR_
  - SAM_
  - GOPR
  - GP_
  - DJI_
  - IMG-
  - PXL_
  - Screenshot_
